# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.7.0
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 14.0
org_name: OpenEMS Association e.V.
org_slug: OpenEMS
rebel_module_groups: []
repo_description: This repository provides a Odoo addon to use Odoo as Metadata provider
  for OpenEMS Backend
repo_name: Odoo for OpenEMS Backend
repo_slug: odoo-openems
repo_website: https://openems.io
travis_apt_packages: []
travis_apt_sources: []
